#!/bin/bash

echo "Install systemd service for depthPressureReader"
cp depthPressureReader.service /lib/systemd/system/depthPressureReader.service
chown root.root /lib/systemd/system/depthPressureReader.service

sudo systemctl enable depthPressureReader.service
